name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
      - name: Run tests in dev shell
        run: |
          nix develop -c bash -lc 'python --version && pytest -q'
      - name: Lint
        run: |
          nix develop -c shellcheck plugin/flake-overrides.bash
